
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Build success
      - name: chek node version
        run: node -v

  Tests:
    name: Tests
    runs-on: self-hosted
      
    steps:      
      - name: Run a one-line script
        run: echo Test success
  Deploy:
    name: Deploy
    runs-on: self-hosted
      
    steps:      
      - name: Run a one-line script
        run: echo deploy success

  Clean:
    name: Clean
    runs-on: self-hosted
      
    steps:      
      - name: Run a one-line script
        run: echo clean success
